### ISSUE TITLE
Make tests that give coverage reports

### ISSUE THREAD

**Issue by UARTman** [learning-at-home/hivemind#14]
CodeCov, while being pretty useless right now, will be essential at some point in the future, when our tests will be numerous.

**Comment by UARTman** [comment]
CI now does it, even if currently it does nothing

**Comment by justheuristic** [comment]
@UARTman Could you please provide a working example?
For instance, tests/benchmark_throughput covers TesseractRuntime functionality and basically nothing else. Can we incorporate it, get our measely 0.0001% coverage and compute it automatically after each push?

**Comment by justheuristic** [comment]
merged into #2
