### ISSUE TITLE
Quantile compression [benchmark convergence]

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#151]
* [x] Implement a script that replaces gradients with their 8-bit quantiles
* [x] Check convergence with ResNet50
https://github.com/kuangliu/pytorch-cifar
(use nora rtx8000)
* [x] Check convergence with 8 micro-batches that are individually compressed, averaged and compressed again

**Comment by mponty** [comment]
- Implementation of approximated 8-bit quantile compression [here](https://github.com/mponty/hivemind/blob/int8_compression/hivemind/utils/grpc.py#L218).
- [Here](https://wandb.ai/montyponty/resnet_grad_compress) are graphs with convergence curves of the tensor compression experiments. Set up:  Resnet50, CIFAR10, 2 workers, synchronization/compression every 8 batches. Final run with latest compression approach is under `int8_avg_compress_all_master` label.
- PR: https://github.com/learning-at-home/hivemind/pull/202

**Comment by justheuristic** [comment]
Done in #202 

Thanks!
