### ISSUE TITLE
Optimize the tests

### ISSUE THREAD

**Issue by mryab** [learning-at-home/hivemind#158]
Right now, our tests can take upwards of 10 minutes both in CircleCI and locally, which slows down the development workflow and leads to unnecessary context switches. We should find a way to reduce the time requirements and make sure it stays that way.

* Identify and speed up the slow tests. Main culprits: multiple iterations in tests using random samples, large model sizes for DMoE tests.
* All the tests in our CI pipelines run sequentially, which increases the runtime with the number of tests. It is possible to use [pytest-xdist](https://pypi.org/project/pytest-xdist/), since the default executor has 2 cores.
* Add a global timeout to ensure that future tests don't introduce any regressions

**Comment by justheuristic** [comment]
Can we consider this solved under #285 ?

**Comment by borzunov** [comment]
@justheuristic I agree that this issue has been addressed in #285, #334, and #343.
