### ISSUE TITLE
Convert hivemind.DHT to use P2P transport

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#185]
__[this PR should be merged into `libp2p` branch]__

Currently, hivemind.DHT relies on gRPC transport, created [here](https://github.com/learning-at-home/hivemind/blob/master/hivemind/dht/protocol.py#L53-L64).

All communication is done through 3 RPCs:
- `call_ping`/`rpc_ping` - get acquainted with a peer and validate availability
- `call_store`/`rpc_store` - request a peer to store one or more DHT entries
- `call_find`/`rpc_find` - request a peer to return a value for a given key OR a list of neighbors that are more likely to provide the given value

The quest is to switch these 3 RPCs to P2P.add_handler / P2P.call instead of gRPC

__Simplified RPC handler:__
* [x] create a simplified `P2P.add_unary_handler` interface that accepts one protobuf message and returns one protobuf message
  * [x] basically, it should add a special handler that deserializes protobuf, calls function and serializes the result (or error)
  * [x] `async def add_unary_handler(self, name, handle, input_protobuf_type, output_protobuf_type)`
  * [x] rpc signature can be `async def add_unary_handler(request: InputProtobufType, context: P2PContext) -> InputProtobufType`:
     * [x] P2P should internally check that the result is indeed InputProtobufType
     * [x] if given wrong protobuf type as input or if handler returns wrong protobuf type, P2P should fail gracefully
     * [x] P2P.add_unary_handler should propagate repr(Exception) to the requester
     * [x] P2PContext should have access to StreamInfo (including sender ID)

__DHT internals conversion:__
* [x] In [protocol.py](https://github.com/learning-at-home/hivemind/blob/master/hivemind/dht/protocol.py#L53-L64): Instead of creating a grpc.aio.server, create a hivemind.P2P and register rpc_* handlers
* [x] switch `rpc_*` handlers to be compatible with unary handler signature (or vice versa compatible)
* [x] in DHTNode, listen=True/False, listen_on and endpoint should be forwarded to P2P

* __Switch from ipv4 endpoints to libp2p endpoints:__
   * [ ] generate `DHTProtocol.node_id` as `DHTID.generate(from=P2P.id)` 
   * [x] use libp2p ID instead of endpoint in `DHTProtocol.routing_table`
   * [x] use libp2p ID instead of endpoint in [DHTNode.blacklist](https://github.com/learning-at-home/hivemind/blob/master/hivemind/dht/node.py#L71)
   * [x] Ensure that:
       * [x] Routing table `routing.py` now uses libp2p ID as endpoints
       * [x] DHTNode `node.py` now uses libp2p IDs for find_nearest_nodes/store_many/get_many_by_id
       * [x] traverse_dht `traverse.py` now uses libp2p IDs instead of endpoints
       * In general, hivemind.DHT internal classes should not know about ipv4 addresses and ports, only P2P should
    * [x] update & run tests: [`test_dht_node.py`](https://github.com/learning-at-home/hivemind/blob/master/tests/test_dht_node.py)

__hivemind.DHT conversion:__
For now, let's delay this step until we're done with DHTNode

**Comment by borzunov** [comment]
Finished in #296.
