### ISSUE TITLE
[Feature Request] examples and more documentation

### ISSUE THREAD

**Issue by flozi00** [learning-at-home/hivemind#206]
**Is your feature request related to a problem? Please describe.**
getting started is not easy to understand

**Describe the solution you'd like**
more documentation and real code examples

**Describe alternatives you've considered**

**Additional context**
https://huggingface.co/EleutherAI/gpt-neo-2.7B

The open source variant of gpt3 by eleuther is published on huggingface modelhub. It takes massively computi9ng power to finetune or pretrain the model, so I thought about starting an open process anyone who wants to train the model for similar or same tasks could join.
Furthermore the wav2vec speech recognition model was published on huggingface hub too, many people without enough computing power would like to train it for their language.
could you provide for example an docker or colab notebook how to start training language models using transformers library ?

**Comment by justheuristic** [comment]
We agree and we are working on tutorials right now (ETA 2 weeks).

If you're willing to contribute, we could use you as an external tester to assure that the tutorials are readable and easy to understand. What do you think of that?

**Comment by flozi00** [comment]
Testing is no problem, maybe it would very good because I have never worked before with this library.
Just don't have enough time to learn it myself from scratch, but think it would be amazing to have examples and ready to use scripts for the transformers library to train large Lm's.

**Comment by justheuristic** [comment]
We merged the ALBERT tutorial into master:
https://github.com/learning-at-home/hivemind/tree/master/examples/albert
Requests and suggestions are very welcome!

We're also running semi-regular public training runs with volunteers RN. Please tell us if you're interested (as a local peer, google colab peer or codebase contributor).

**Comment by justheuristic** [comment]
[closed as inactive. Feel free to create a new issue if necessary]
