### ISSUE TITLE
Convert hivemind.Server/RemoteModuleCall/RemoteCallMany to libp2p backend

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#242]
[depends on #238 to be merged ]
After we've implemented P2P transport with nat traversal, we should switch the main components to libp2p backend to take advantage of this new transport.

One of three main components is `hivemind.server.Server` and its counterpart `hivemind.client.RemoteExpert`

On a client side, hivemind creates a RemoteExpert pytorch module that calls experts via [`_RemoteModuleCall`](https://github.com/learning-at-home/hivemind/blob/master/hivemind/client/expert.py#L70-L104) (and [`_RemoteCallMany`](https://github.com/learning-at-home/hivemind/blob/master/hivemind/client/moe.py#L153-L162) for DMoE)

A server receives incoming connections with several [`ConnectionHandler`](https://github.com/learning-at-home/hivemind/blob/master/hivemind/server/connection_handler.py) processes running in parallel. These processes run gRPC servers and hence should be switched to libp2p.

* Checklist
   * [x] find some way to attach several processes to one RPC (as in server/connection_handler.py)
   * [ ] make sure it passes `tests/test_moe.py`
   * [ ] make sure it passes `tests/test_training.py`
   * [x] tune performance in `tests/benchmark_througphput.py`

**Comment by GreenFatGuy** [comment]
working on it

**Comment by justheuristic** [comment]
Current status:
- we're broken DHT get_experts (or declare experts) capability, gotta fix it
- there's some error when dealing with large messages (@deniskamazur PLZ add an example that fails, e.g. for benchmark_throughput)
- gotta merge changes from master

**Comment by GreenFatGuy** [comment]
Current progress:

* merge of `master` is done
* dht bug is fixed, the problem was that dht had not enough data to initialize RemoteExpert properly + it should be constructed on client side now
* working on fixes for big benchmarks: the plan is to split data into partitions.

**Comment by GreenFatGuy** [comment]
Current status:

Implemented streaming for backward and forward for moe/expert/RemoteModuleCall. Now we split all inputs and outputs for forward/backward into smaller parts before sending, then stream this parts and assemble again on the other end. There is no problem with big batches now.

In plans:
 * fix tests for new moe expert/server on p2p
 * implement variance in forward/backward call: if we can - do non-streaming version (old one), if don't - new one with streaming. This could possibly increase throughput (do experiment).
 * try different architectures. I need a server for it, because my machine can not do this

**Comment by GreenFatGuy** [comment]
Current status:
 - Add forwarding of P2P instance from current DHT to the RemoteExpert (reminder: remote expert are now more complex than just address of the host, they have P2P instance inside, thus it is created in a lazy way on client side)
 - Achieved better performance on benchmark by using multiple instances of connection handler. This achieved by some changes in p2p daemon. (TODO: link to the changes)
 - Beam search updated to handle lazy expert creation. Test `tests/test_dht_experts.py` passed.
 
 In plans:
  - fix other tests (firstly `tests/test_training.py` and `tests/test_moe.py`, then others if any broken)
  - do pull request

**Comment by borzunov** [comment]
Done in #470. Further minor issues are listed in #478.
