### ISSUE TITLE
[REFACTOR] general codebase updates for v0.10

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#275]
Extracted from #98 

- [x] Switch away from wildcard imports (from ... import *) in favor of explicit symbols
- [x] move functionality away from `__init__.py` files
- [x] move hivemind.client.averaging -> hivemind.averaging
   - [x] make sure this does not break application code
- [x] replace prints from benchmark_dht/averaging with logging.info
- [x] see if there are fixable warnings
   - tests still raise warning about non-copyable ndarray in (de)serialize_torch_tensor
- [ ] create an issue template for `[REFACTOR]`
- [x] (after libp2p integration) rename hivemind.utils.grpc -> hivemind.utils.protobuf ?
   -  Renamed to `hivemind.utils.streaming` in #470

**Comment by borzunov** [comment]
Mostly done, v0.10 was released a long time ago :)
