### ISSUE TITLE
Retire prefetch_generator

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#289]
We're using this dependency in one spot, where it can be replaced with ~5 lines of native code.
Would be great to remove it

**Comment by justheuristic** [comment]
... somehow this is issue is still not obsolete

**Comment by borzunov** [comment]
This is a light dependency that is fully under our control and doesn't bring further deps. Thus, I think profit from removing it is less than efforts needed to prepare the corresponding PR :) Feel free to reopen this if you disagree.
