### ISSUE TITLE
[REFACTOR] consider asyncio utils libraries

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#292]
Currently, we use a set of asynchronous functions defined in hivemind.utils.asyncio . It may be a good idea to switch to some of the existing asyncio utils.

The only caveat is that the replacement for async_map should run the corresponding function in executor, otherwise we will lose responsiveness in some cases.

**Comment by borzunov** [comment]
I think switching to an existing asyncio util lib requires huge efforts:

- There's no widely-used asyncio util lib, so the lib itself is likely to be buggy
- The lib's functions are likely to be incompatible in some edge cases
- Testing concurrent code is hard, so it's gonna be hard to reveal these edge cases

Thus, I think the profit from switching is less than efforts needed to prepare the corresponding PR :) Feel free to reopen this if you disagree.
