### ISSUE TITLE
Convert hivemind to libp2p backend to implement NAT traversal

### ISSUE THREAD

**Issue by borzunov** [learning-at-home/hivemind#314]
_This checklist is created by @justheuristic and @deniskamazur as a part of #165 and moved here after closing that PR._

Our current strategy is to use [go-libp2p-daemon](https://github.com/libp2p/go-libp2p-daemon) to connect between users
* __Compile libp2p daemon__
   * [x] Build libp2p daemon on setup
      * [x] Ensure that we build a specific version of go-libp2p-daemon
   * [x] Make sure p2pd is included with pypi package
   * [x] Find out the optimal parameters for nat traversal

* __Implement a P2Pd controller (codename hivemind.P2P)__
   * [x] Make sure it always kills the p2pd process on termination (both with del and with kill -9)
   * [x] add_rpc_servicer (simlar to GRPC)
       * [x] Ensure that it supports asyncio
       * [x] Ensure that it is process-safe
   * [x] Add unit tests for hivemind.P2P
   * [x] Figure out the user experience (e.g. spawn P2P when DHT is created)
   * [x] Figure out the codebase layout (e.g. hivemind.dht.p2p)
      * Considerations:
          * Move synchronization and get_dht_time to P2P? (rationale: support clock correction)
          * Move dht's validate=True to P2P?
          * In future, can we merge hivemind.DHT into libp2p's DHT? (expiration, conflict resolution, atomic subkey addition, performance)

* __Convert `hivemind.dht.DHT`__
   * [x] support the equivalent of gRPC.unary_unary RPC - get one message, return one message
   * [x] hivemind.dht.DHTProtocol to p2pd
   * [x] ensure that we can deal with stale connections
   * [x] make sure it passes `tests/test_dht_node.py`
   * [x] make sure it passes `tests/test_dht_experts.py`
   * [x] tune performance for `tests/benchmark_dht` with 1000 nodes and 16384 experts

* __Convert `hivemind.client.averaging.DecentralizedAverager` to p2pd__
   * [x] figure out how to implement rpc_join_group:
       * maybe support the equivalent of gRPC.stream_stream RPC (for averager)
   * [x] ensure that large messages do not cause reduced throughput
       * [x] test if split_into_parts is still required. If not, remove it
   * [x] make sure it passes `tests/test_averaging.py`
   * [x] tune performance with `tests/benchmark_averaging.py`

* __Convert `hivemind.dht.Server`__
   * [ ] find some way to attach several processes to one RPC (as in server/connection_handler.py)
   * [ ] make sure it passes `tests/test_moe.py`
   * [ ] make sure it passes `tests/test_training.py`
   * [ ] tune performance in `tests/benchmark_througphput.py`

* __`Train something from behind NAT`__
    * [x] make sure ALBERT-v2-large runs
    * [x] ... with at least one participant under NAT
    * [x] ... with all but one participant under NAT
    * [x] ... for at least 48 hours

* Bonus quests:
    * [x] investigate: __try libp2p relays!__ (TURN)

**Comment by justheuristic** [comment]
Added link to #470 : when merged, that pull request will complete the checklist from this issue.
