### ISSUE TITLE
Forward errors from P2P creation

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#322]
Currently, staring P2P with bad parameters results in the following error message:
![image](https://user-images.githubusercontent.com/3491902/125806236-7f48146d-a433-41a4-a28e-abdc9167d4ed.png)

While the actual error message is hidden:

![image](https://user-images.githubusercontent.com/3491902/125806191-7b9352d9-f532-494e-92fc-1181d619ef90.png)

Can we forward the actual error as a pythonic exception?

**Comment by borzunov** [comment]
Resolved in #343. Works both in a Jupyter notebook and `examples/albert` (the message is visible in the last output line):

<img width="900" alt="Screen Shot 2021-08-03 at 8 54 47 PM" src="https://user-images.githubusercontent.com/8748943/128063117-317f527a-c6f7-4363-8243-5686367ea700.png">

<img width="900" alt="Screen Shot 2021-08-03 at 8 49 39 PM" src="https://user-images.githubusercontent.com/8748943/128063104-34ed4a5d-207e-4c0d-8a8f-10fdab300bc9.png">
`.
