### ISSUE TITLE
Periodically load state in run_training_monitor without necessarily uploading it

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#332]
Currently, `examples/albert/run_training_monitor.py` has a functionality for saving state, AFAIR it cannot be enabled if a machine has no internet access.

Please implement some way that we can ask monitor to just load stuff every few minutes as a backup if all GPU peers fail.

**Comment by justheuristic** [comment]
@yhn112 can you please post and example config for that?

**Comment by justheuristic** [comment]
@yhn112 can we consider this done?
if so - please post the corresponding CLI args for posterity

**Comment by yhn112** [comment]
To enable state loading one should pass `--store_checkpoins` flag.
And also ` --model_config_path PATH_TO_CONFIG` if there is no internet access.
