### ISSUE TITLE
Move dummy Server to a separate process in tests

### ISSUE THREAD

**Issue by mryab** [learning-at-home/hivemind#34]
Currently for testing purposes we create hivemind.Server in a background thread for each test. It seems that CUDA initialization happens somewhere in this thread, so we can't have two tests using server communication in a single file (otherwise we have CUDA initialization error). 

A better testing strategy would be to start a server in a separate process, because that is intended usage of a server and the entire backend logic is built around process (or network) communication. Moreover, it should enable us to run tests on GPU given the previous paragraph.

**Comment by justheuristic** [comment]
implemented in https://github.com/learning-at-home/hivemind/blob/master/tests/test_utils/run_server.py#L96
