### ISSUE TITLE
Missing "params" when initializing "Optimizer" in albert example 

### ISSUE THREAD

**Issue by finger92** [learning-at-home/hivemind#431]
In file "examples/albert/run_trainer.py", line 264
When initializing "Optimizer", set "offload_optimizer" to True while not giving "params" argument. It will show this error when running "run_trainer.py":
`ValueError: To enable offload_optimizer or delayed updates, please initialize Optimizer as hivemind.Optimizer(..., params=params, optimizer=lambda params: create_opt(params)`

**Comment by finger92** [comment]
Well, I realized that the optimizer and scheduler should write in lambda way, so I guess the fix should be something like:

...
params=optimizer_grouped_parameters,
optimizer=partial(Lamb, ...),
scheduler=partial(get_linear_schedule_with_warmup, ...),

**Comment by justheuristic** [comment]
Your fix should indeed work, please contact us if there are any further issues. I will keep this one open for a few more days just in case

**Comment by borzunov** [comment]
We've just fixed the example in #433, thanks a lot for reporting the problem.

Feel free to reopen/create new issues if there's any further problems!
