### ISSUE TITLE
[Feature Request] Create docker image for WSL2

### ISSUE THREAD

**Issue by kotenok2000** [learning-at-home/hivemind#461]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by justheuristic** [comment]
Hi, Kirill

To the best of my understanding, once you installed WSL2 with GPU driver, __running hivemind inside WSL is the same as running on linux__.

We will eventually write an extended documentation for WSL, but this is not the highest priority r/n. If you have some specific use case that you want help with, we can help with that.

**Comment by kotenok2000** [comment]
I also want to know what is minimum gpu to use.
I have gtx 1650 4 gb is it good enough?

**Comment by justheuristic** [comment]
It depends on what model you're running. In NLP, 4GB is known to be enough for albert-xlarge (~same as bert-large).

**Comment by justheuristic** [comment]
Closing this issue as inactive. If you have any other comments, feel free to open a new one.
