### ISSUE TITLE
[BUG] Global connection not working

### ISSUE THREAD

**Issue by Lednik7** [learning-at-home/hivemind#472]
**Describe the bug**
I tried work via kaggle to start distributive learning but no connection
Error:
```python3
hivemind.p2p.p2p_daemon_bindings.control.P2PDaemonError: Daemon failed to start: 2022/05/24 19:21:27 failed to connect to bootstrap peers
```

**To Reproduce**

notebook1:
```python3
!git clone https://github.com/learning-at-home/hivemind
!cd hivemind && pip install -e . --no-use-pep517
```
```python3
%%writefile run.py

import hivemind

dht = hivemind.DHT(
    host_maddrs=["/ip4/0.0.0.0/tcp/0", "/ip4/0.0.0.0/udp/0/quic"],
    start=True)

print('\n'.join(str(addr) for addr in dht.get_visible_maddrs()))
print("Global IP:", hivemind.utils.networking.choose_ip_address(dht.get_visible_maddrs()))

input()
```
```python3
!python run.py
```
```
/ip4/172.19.2.2/tcp/34845/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA
/ip4/127.0.0.1/tcp/34845/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA
/ip4/172.19.2.2/udp/40461/quic/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA
/ip4/127.0.0.1/udp/40461/quic/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA
Global IP: 172.19.2.2
```

notebook2:
```python3
!git clone https://github.com/learning-at-home/hivemind
!cd hivemind && pip install -e . --no-use-pep517
```
```python3
%%writefile run.py

import hivemind

dht = hivemind.DHT(
    host_maddrs=["/ip4/0.0.0.0/tcp/0", "/ip4/0.0.0.0/udp/0/quic"],
    initial_peers=[
        "/ip4/172.19.2.2/tcp/34845/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA",
        "/ip4/172.19.2.2/udp/40461/quic/p2p/QmU6gBb1x554TadHwkzX4LRyXK6vzmhokCnUSK4H5XNEMA",
    ], start=True)

input()
```
```python3
!python run.py
```
```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    ], start=True)
  File "/kaggle/working/hivemind/hivemind/dht/dht.py", line 86, in __init__
    self.run_in_background(await_ready=await_ready)
  File "/kaggle/working/hivemind/hivemind/dht/dht.py", line 143, in run_in_background
    self.wait_until_ready(timeout)
  File "/kaggle/working/hivemind/hivemind/dht/dht.py", line 146, in wait_until_ready
    self._ready.result(timeout=timeout)
  File "/kaggle/working/hivemind/hivemind/utils/mpfuture.py", line 257, in result
    return super().result(timeout)
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
hivemind.p2p.p2p_daemon_bindings.control.P2PDaemonError: Daemon failed to start: 2022/05/24 19:21:27 failed to connect to bootstrap peers
```

**Environment**
Please list:
* cpu mode
* internet on
* Python 3.7.12
* hivemind==1.1.0.dev0
* Please copy and paste the output from pytorch [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
```
Collecting environment information...
PyTorch version: 1.11.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.107+-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] pytorch-ignite==0.4.9
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.11.0+cpu
[pip3] torchaudio==0.11.0+cpu
[pip3] torchmetrics==0.6.2
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cpu
[conda] mkl                       2022.0.1           h8d4b97c_803    conda-forge
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-ignite            0.4.9                    pypi_0    pypi
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] torch                     1.11.0+cpu               pypi_0    pypi
[conda] torchaudio                0.11.0+cpu               pypi_0    pypi
[conda] torchmetrics              0.6.2                    pypi_0    pypi
[conda] torchtext                 0.12.0                   pypi_0    pypi
[conda] torchvision               0.12.0+cpu               pypi_0    pypi
```

**Comment by justheuristic** [comment]
Hi! (and thanks for the report!)

Did I understand correctly that both peers are using kaggle and there are no other peers?

If so: i'm afraid that we'll need at least one peer (possibly without GPU) that has a publicly visible IP address, such as a homelab or cloud vm.

**Why this is necessary:** two non-public peers can communicate through either [hole punching](https://en.wikipedia.org/wiki/UDP_hole_punching) or through [circuit relay](https://docs.libp2p.io/concepts/circuit-relay/). Both options require at least one extra device to help the two peers communicate: either as a relay, or for initial metadata exchange (in case of UDP hole punching). If your swarm has one or more such devices, other peers will be able to communicate with each other.

**Where to get this kind of access:**
- the easiest way is to use a cheapo dedicated server. Our colleagues at NCAI used pebblehost minecraft servers for this, but any other cheap hosting would do. You can read more in [this readme](https://github.com/NCAI-Research/CALM) in "Setting up auxiliary peers" section
- the hard (but Ъ) way is to configure your home/lab pc to act as a connection broker -- but you will likely need to configure a static IP address with your ISP
- the easy, but risky (and extra Ъ) way would be to use IPFS nodes as connection brokers. You can read more on that in [our dht tutorial](https://learning-at-home.readthedocs.io/en/latest/user/dht.html). However, we found that way to be somewhat unreliable.

**Comment by justheuristic** [comment]
We (seemingly) resolved these questions over a quick call. I'm closing this issue. If you have any other concerns, please open a new one.

**Comment by Lcomerun** [comment]
> 你好！（感谢您的报告！
> 
> 我是否正确理解了两个对等体都在使用 kaggle，而没有其他对等体？
> 
> 如果是这样：恐怕我们至少需要一个具有公开可见 IP 地址的对等体（可能没有 GPU），例如 homelab 或云 vm。
> 
> **为什么这样做是必要的：**两个非公共对等体可以通过[打孔](https://en.wikipedia.org/wiki/UDP_hole_punching)或[电路中继](https://docs.libp2p.io/concepts/circuit-relay/)进行通信。这两个选项都需要至少一个额外的设备来帮助两个对等体进行通信：作为中继，或用于初始元数据交换（在 UDP 打孔的情况下）。如果您的 swarm 有一个或多个此类设备，则其他对等体将能够相互通信。
> 
> **从何处获得此类访问权限：**
> 
> * 最简单的方法是使用 Cheapo 专用服务器。我们在 NCAI 的同事为此使用了 pebblehost minecraft 服务器，但任何其他廉价托管都可以。您可以在[本自述文件的](https://github.com/NCAI-Research/CALM) “设置辅助对等体” 部分中阅读更多内容
> * 困难的（但 Ъ）方法是将您的家庭/实验室 PC 配置为连接代理 - 但您可能需要使用 ISP 配置静态 IP 地址
> * 简单但有风险（且额外的 Ъ）方法是使用 IPFS 节点作为连接代理。您可以在[我们的 dht 教程](https://learning-at-home.readthedocs.io/en/latest/user/dht.html)中阅读更多相关信息。但是，我们发现这种方式有些不可靠。

I encountered the same issue, how did you resolve it?
