### ISSUE TITLE
[Feature Request] Supporting RWKV (a RNN that can match transformer LM & zero-shot performance at 1B+ params)

### ISSUE THREAD

**Issue by BlinkDL** [learning-at-home/hivemind#496]
Hi guys. The Hivemind concept is great. And it will be even better if we can run large models on edge devices to make it fully decentralized.

Regarding this, I am working on RWKV, which might be the only RNN (no attention!) that can match transformer LM & zero-shot performance at 1B+ params:
https://www.reddit.com/r/MachineLearning/comments/vzr6ie/r_rwkv3_scaling_rnn_to_15b_and_reach_transformer/

Being a RNN, it's very friendly for edge devices - the inference is extremely simple (only requires matrix-vector multiplications) and saves VRAM.

Probably we can collaborate to decentralize RWKV training & inference too :)

RWKV github: https://github.com/BlinkDL/RWKV-LM

RWKV discord: https://discord.gg/bDSBUMeFpc

**Comment by BlinkDL** [comment]
Thanks for the suggestions :) I will take a look.

**Comment by borzunov** [comment]
I'll close this for now, but please don't hesitate to reopen this issue and/or reach us on Discord or via a voicechat if you start implementing RWKV and need any help (or meet any technical difficulties) :)
