### ISSUE TITLE
[BUG] GradScaler does not work with torch 2.3.0

### ISSUE THREAD

**Issue by samsja** [learning-at-home/hivemind#610]
**Describe the bug**

GradScaler is not working anymore with pytorch 2.3.0 

This 

**To Reproduce**
```python
from torch.cuda.amp.grad_scaler import OptState, _refresh_per_optimizer_state
```

this is failing now with pytorch 2.3. Which make it impossible to import hivemind GradScaler because of this [line](https://github.com/learning-at-home/hivemind/blob/d20e81017481aa2028efc33217522248aabd7d95/hivemind/optim/grad_scaler.py#L8)

**Environment**
Please list:
* python version (e.g. 3.10.13);
* hivemind.__version__; (master, 1.2.0.dev0)

**Comment by rohrl** [comment]
+1
